" Name:         DarkGreen
" Description:  Template for dark colorscheme
" Author:       Raku <raku@exhibition.jp>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Change:  2024 Oct 16

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'darkgreen'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = has('gui_running') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link Removed diffRemoved
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#141615', '#fda596', '#749c3b', '#a98f27', '#886ee7', '#d280be', '#7eaadc', '#b2b9a9', '#425049', '#ffc6bc', '#e8ffc9', '#ffefaf', '#b5bbff', '#ebb1dc', '#afdff0', '#dadfd3']
endif
if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
  hi Terminal guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=fg guibg=#141615 gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi CursorColumn guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi CursorLine guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi CursorLineNr guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi DiffAdd guifg=#b2b9a9 guibg=#141615 gui=reverse cterm=reverse
hi DiffChange guifg=#b2b9a9 guibg=#141615 gui=reverse cterm=reverse
hi DiffDelete guifg=#b2b9a9 guibg=#141615 gui=reverse cterm=reverse
hi DiffText guifg=#b2b9a9 guibg=#141615 gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi EndOfBuffer guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi ErrorMsg guifg=#b2b9a9 guibg=#141615 gui=reverse cterm=reverse
hi FoldColumn guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Folded guifg=#b2b9a9 guibg=#141615 gui=italic cterm=italic
hi IncSearch guifg=#b2b9a9 guibg=#141615 gui=standout cterm=reverse
hi LineNr guifg=#52746a guibg=#141615 gui=NONE cterm=NONE
hi MatchParen guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi ModeMsg guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi MoreMsg guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi NonText guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Pmenu guifg=#b2b9a9 guibg=#52746a gui=NONE cterm=NONE
hi PmenuSbar guifg=#b2b9a9 guibg=#2b463e gui=NONE cterm=NONE
hi PmenuSel guifg=#e8ffc9 guibg=#52746a gui=reverse cterm=reverse
hi PmenuThumb guifg=#b2b9a9 guibg=#e8ffc9 gui=NONE cterm=NONE
hi Question guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Search guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi SignColumn guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi SpecialKey guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi SpellBad guifg=#b2b9a9 guibg=#141615 guisp=#fda596 gui=NONE cterm=NONE
hi SpellCap guifg=#b2b9a9 guibg=#141615 guisp=#886ee7 gui=NONE cterm=NONE
hi SpellLocal guifg=#b2b9a9 guibg=#141615 guisp=#d280be gui=NONE cterm=NONE
hi SpellRare guifg=#b2b9a9 guibg=#141615 guisp=#7eaadc gui=reverse cterm=reverse
hi StatusLine guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi StatusLineNC guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi TabLine guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi TabLineFill guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi TabLineSel guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Title guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi VertSplit guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Visual guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi VisualNOS guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi WarningMsg guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi WildMenu guifg=#b2b9a9 guibg=#141615 gui=NONE cterm=NONE
hi Comment guifg=#b2b9a9 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#b2b9a9 guibg=#141615 gui=reverse cterm=reverse
hi Identifier guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#b2b9a9 guibg=NONE gui=NONE cterm=NONE
hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#141615 gui=NONE cterm=NONE
hi ToolbarButton guifg=#b2b9a9 guibg=#141615 gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=144 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=144 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=144 ctermbg=233 cterm=NONE
    hi Terminal ctermfg=144 ctermbg=233 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=233 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=144 ctermbg=233 cterm=NONE
  hi CursorColumn ctermfg=144 ctermbg=233 cterm=NONE
  hi CursorLine ctermfg=144 ctermbg=233 cterm=NONE
  hi CursorLineNr ctermfg=144 ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=144 ctermbg=233 cterm=reverse
  hi DiffChange ctermfg=144 ctermbg=233 cterm=reverse
  hi DiffDelete ctermfg=144 ctermbg=233 cterm=reverse
  hi DiffText ctermfg=144 ctermbg=233 cterm=bold,reverse
  hi Directory ctermfg=144 ctermbg=233 cterm=NONE
  hi EndOfBuffer ctermfg=144 ctermbg=233 cterm=NONE
  hi ErrorMsg ctermfg=144 ctermbg=233 cterm=reverse
  hi FoldColumn ctermfg=144 ctermbg=233 cterm=NONE
  hi Folded ctermfg=144 ctermbg=233 cterm=italic
  hi IncSearch ctermfg=144 ctermbg=233 cterm=reverse
  hi LineNr ctermfg=66 ctermbg=233 cterm=NONE
  hi MatchParen ctermfg=144 ctermbg=233 cterm=NONE
  hi ModeMsg ctermfg=144 ctermbg=233 cterm=NONE
  hi MoreMsg ctermfg=144 ctermbg=233 cterm=NONE
  hi NonText ctermfg=144 ctermbg=233 cterm=NONE
  hi Pmenu ctermfg=144 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=144 ctermbg=23 cterm=NONE
  hi PmenuSel ctermfg=193 ctermbg=66 cterm=reverse
  hi PmenuThumb ctermfg=144 ctermbg=193 cterm=NONE
  hi Question ctermfg=144 ctermbg=233 cterm=NONE
  hi Search ctermfg=144 ctermbg=233 cterm=NONE
  hi SignColumn ctermfg=144 ctermbg=233 cterm=NONE
  hi SpecialKey ctermfg=144 ctermbg=233 cterm=NONE
  hi SpellBad ctermfg=144 ctermbg=233 cterm=NONE
  hi SpellCap ctermfg=144 ctermbg=233 cterm=NONE
  hi SpellLocal ctermfg=144 ctermbg=233 cterm=NONE
  hi SpellRare ctermfg=144 ctermbg=233 cterm=reverse
  hi StatusLine ctermfg=144 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=144 ctermbg=233 cterm=NONE
  hi TabLine ctermfg=144 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=144 ctermbg=233 cterm=NONE
  hi TabLineSel ctermfg=144 ctermbg=233 cterm=NONE
  hi Title ctermfg=144 ctermbg=233 cterm=NONE
  hi VertSplit ctermfg=144 ctermbg=233 cterm=NONE
  hi Visual ctermfg=144 ctermbg=233 cterm=NONE
  hi VisualNOS ctermfg=144 ctermbg=233 cterm=NONE
  hi WarningMsg ctermfg=144 ctermbg=233 cterm=NONE
  hi WildMenu ctermfg=144 ctermbg=233 cterm=NONE
  hi Comment ctermfg=144 ctermbg=NONE cterm=italic
  hi Constant ctermfg=144 ctermbg=NONE cterm=NONE
  hi Error ctermfg=144 ctermbg=233 cterm=reverse
  hi Identifier ctermfg=144 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=144 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=144 ctermbg=NONE cterm=NONE
  hi Special ctermfg=144 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=144 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=144 ctermbg=NONE cterm=NONE
  hi Type ctermfg=144 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=144 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi ToolbarButton ctermfg=144 ctermbg=233 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ModeMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=DarkGreen cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=DarkGreen cterm=NONE
  hi PmenuSel ctermfg=LightGreen ctermbg=Green cterm=reverse
  hi PmenuThumb ctermfg=LightGrey ctermbg=LightGreen cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Error ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi Identifier ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi debugBreakpoint term=reverse
  hi debugPC term=reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #141615                   ~         Black
" Color: red           #FDA596                   ~         DarkRed
" Color: green         #749C3B                   ~         DarkGreen
" Color: yellow        #A98F27                   ~         DarkYellow
" Color: blue          #886EE7                   ~         DarkBlue
" Color: magenta       #D280BE                   ~         DarkMagenta
" Color: cyan          #7EAADC                   ~         DarkCyan
" Color: white         #B2B9A9                   ~         LightGrey
" Color: brightblack   #425049                   ~         DarkGrey
" Color: brightred     #FFC6BC                   ~         LightRed
" Color: brightgreen   #E8FFC9                   ~         LightGreen
" Color: brightyellow  #FFEFAF                   ~         LightYellow
" Color: brightblue    #B5BBFF                   ~         LightBlue
" Color: brightmagenta #EBB1DC                   ~         LightMagenta
" Color: brightcyan    #AFDFF0                   ~         LightCyan
" Color: brightwhite   #DADFD3                  231        White
" Color: accentdark    #52746A                   ~         DarkGreen
" Color: accentbg      #182F28                   ~         Black
" Color: accentborder  #2B463E                   ~         DarkGreen
" Color: accentlight   #52746A                   ~         Green
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
